name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "25 6 * * *"  # Schedule it to run daily at 18:00 UTC (adjust the time zone as needed)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Profile 3D Contribution
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate GitHub Profile 3D Contribution
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: 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   # Replace with your GitHub token
          USERNAME: iamtmj    # Replace with your GitHub username

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generated GitHub Profile 3D Contribution"
          git push
